[package]
name        = "msbe-provider-modrinth"
description = "The Modrinth provider adapter."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
readme.workspace       = true
keywords.workspace     = true
categories.workspace   = true
publish.workspace      = true

[lints]
workspace = true

[features]
test = ["dep:sha2"]

[dependencies]
msbe-fsops           = { version = "0.0.0", path = "../msbe-fsops" }
msbe-plan-schema     = { version = "0.0.0", path = "../msbe-plan-schema" }
msbe-provider-api    = { version = "0.0.0", path = "../msbe-provider-api" }
serde.workspace      = true
serde_json.workspace = true
thiserror.workspace  = true
sha2 = { workspace = true, optional = true }

[dev-dependencies]
sha2.workspace = true
tempfile.workspace = true
