[package]
name        = "msbe-provider-direct"
description = "The direct HTTPS URL provider adapter."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
readme.workspace       = true
keywords.workspace     = true
categories.workspace   = true
publish.workspace      = true

[lints]
workspace = true

[dependencies]
msbe-core           = { version = "0.0.0", path = "../msbe-core" }
msbe-fsops          = { version = "0.0.0", path = "../msbe-fsops" }
msbe-provider-api   = { version = "0.0.0", path = "../msbe-provider-api" }
thiserror.workspace = true

[dev-dependencies]
sha2.workspace     = true
tempfile.workspace = true
