[package]
name        = "msbe-pack"
description = "Portable modpack manifest import and export."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
readme.workspace       = true
keywords.workspace     = true
categories.workspace   = true
publish.workspace      = true

[lints]
workspace = true

[dependencies]
msbe-fsops = { version = "0.0.0", path = "../msbe-fsops" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
